name: Integration Tests (uv + pyproject.toml)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies with uv
        run: |
          uv venv
          uv pip install -e.

      - name: Run tests
        run: |
          uv run pytest
